sudo: required
services:
  - docker

before_install:
  - docker build -t daun/multiple-docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true daun/multiple-docker-react npm test -- --coverage

after_success:
  - docker build -t tuanany73/multi-client ./client
  - docker build -t tuanany73/multi-nginx ./nginx
  - docker build -t tuanany73/multi-server ./server
  - docker build -t tuanany73/multi-worker ./worker

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub
  - docker push tuanany73/multi-client
  - docker push tuanany73/multi-nginx
  - docker push tuanany73/multi-server
  - docekr push tuanany73/multi-worker

